### ISSUE TITLE
It follows the bots username

### ISSUE THREAD

**Issue by mrbm** [social-manager-tools/socialmanagertools-igbot#135]
I watched used the bot to follow the followers from another like minded account, and I noticed that it added my own bot's username in the array of items to follow. Perhaps an if statement should be added to not follow yourself or this indicates instagram has made some changes and what it shows in the follow list has been updated, so perhaps this needs to be updated as well.

**Comment by ptkdev** [comment]
@mrbm Whitelist param not work?

**Comment by mrbm** [comment]
I didn't test the whitelist feature, but to save set up time probably should do a check on itself.

I also noticed that after following somebody and looking at followers, the list is now very limited, I don't know if that's a new change to instagram and something to be reviewed.

**Comment by mrbm** [comment]
I belive they have added a new "timing" and "action" mechanism before showing all the followers.

I see if I manually go to followers, it shows a limited amount of followers then shows "suggestions for you" and then ends the list. Then when scrolling through suggestions for you, scrolling up, then scrolling down it seems to then add followers to the list. But that said, I think you need to review the mechanism for the changes in how insta is allowing followers to be displayed

**Comment by ptkdev** [comment]
Ok, i try solve this in next release.

NOTE: Please use default issue-templates with bot version, mode version and other info. Don't delete issue template.

**Comment by ptkdev** [comment]
Fixed in **latest** release.
