### ISSUE TITLE
improve the comment system

### ISSUE THREAD

**Issue by RamonSaldanha** [social-manager-tools/socialmanagertools-igbot#145]
The comment system is very slow, and in some posts it repeats the comment.

it is as if the robot just kept waiting for new posts instead of going in all the hashtag posts, as it is in the tanned ones.

Other than that, the script is very good, congratulations

**Comment by ptkdev** [comment]
Hi!
Don't is slow, instagram limits is 500 comment's daily. 
500 comment in 24h = sleep time is very long.

I try fix comment repeat in next release :)

**Comment by rzaevtogrul** [comment]
hi there, 
Comments still do not work. Bot wont do anything. 
I tried several configurations

**Comment by ptkdev** [comment]
**Fixed** in Social Manager Tools v0.6.6 and IGBot Library v0.9.18. 
_Remember_: update and use latest chrome version (v75)

[![](https://img.shields.io/badge/donate-paypal-005EA6.svg)](http://paypal.ptkdev.io) [![](https://img.shields.io/badge/donate-patreon-F87668.svg)](http://patreon.ptkdev.io) [![](https://img.shields.io/badge/donate-opencollective-5DA4F9.svg)](http://opencollective.ptkdev.io) [![](https://img.shields.io/badge/buy%20me-coffee-4B788C.svg)](http://coffee.ptkdev.io) [![](https://img.shields.io/badge/help-support@ptkdev.io-fbbc05.svg)](mailto:support@ptkdev.io)
