### ISSUE TITLE
Error install node modules

### ISSUE THREAD

**Issue by DeltaFox0018** [social-manager-tools/socialmanagertools-igbot#149]
### Versions

- **Bot Version:** v0.7.4
- **Node Version:** v8.15.1 (Bot require >= 7.6)
- **NPM Version:** v6.4.1
- **Operating System:** Ubuntu Server 18.04

### Expected Behavior

Once the sudo npm install command is launched, all modules must be installed

### Actual Behavior

When I run the sudo npm install command, I get this error message both with node at version 8.15 and with version 11

> sqlite3@4.0.6 install /home/ubuntu/bot_insta/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.6/node-v57-linux-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.6 and node@8.15.1 (node-v57 ABI, glibc) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.15.0-1032-raspi2
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/ubuntu/bot_insta/node_modules/sqlite3/lib/binding/node-v57-linux-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/ubuntu/bot_insta/node_modules/sqlite3/lib/binding/node-v57-linux-arm64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd /home/ubuntu/bot_insta/node_modules/sqlite3
gyp ERR! node -v v8.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ubuntu/bot_insta/node_modules/sqlite3/lib/binding/node-v57-linux-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/ubuntu/bot_insta/node_modules/sqlite3/lib/binding/node-v57-linux-arm64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ubuntu/bot_insta/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.15.0-1032-raspi2
node-pre-gyp ERR! command "/usr/bin/node" "/home/ubuntu/bot_insta/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ubuntu/bot_insta/node_modules/sqlite3
node-pre-gyp ERR! node -v v8.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ubuntu/bot_insta/node_modules/sqlite3/lib/binding/node-v57-linux-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/ubuntu/bot_insta/node_modules/sqlite3/lib/binding/node-v57-linux-arm64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-03-10T18_11_52_351Z-debug.log

**Comment by ptkdev** [comment]
This is sqlite bug, try `npm install sqlite3@4.0.2 --save`

**Comment by DeltaFox0018** [comment]
keeps giving me the same error, I installed ubuntu server on raspberry the arm64 version, can it be that the error is given by the arm64 version and so I have to install the armhf version?

**Comment by ptkdev** [comment]
If you try build from source? `npm install sqlite3 --build-from-source`

**Comment by ptkdev** [comment]
NPM Sqlite3 is a shit, in the next version it will be abandoned.

**Comment by DeltaFox0018** [comment]
sqlite is not installed and is still in error, thanks for the help. I'm waiting for the new version

**Comment by ptkdev** [comment]
I install without problem with global param:
 `sudo npm install sqlite3@4.0.2 -g --build-from-source` and remove sqlite from `package.json `

**Comment by DeltaFox0018** [comment]
package.json located in the root directory?

**Comment by ptkdev** [comment]
Yes

**Comment by DeltaFox0018** [comment]
The package.json file does not exist in the non-sqlite root directory, even in the one on github

{
  "name": "instagrambotjs",
  "description": "Instagram Bot made with love and Node.js",
  "version": "1.0.0",
  "main": "bot.js",
  "author": "Patryk Rzucidło [@ptkdev] <support@ptkdev.io> (https://ptkdev.it)",
  "license": "GPL-3.0",
  "homepage": "https://instagram.bot.ptkdev.io",
  "repository": {
    "type": "git",
    "url": "https://github.com/social-manager-tools/instagram-bot.js.git"
  },
  "bugs": {
    "url": "https://github.com/social-manager-tools/instagram-bot.js/issues"
  },
  "scripts": {
    "start": "node bot.js",
    "start-forever": "forever -o ./logs/debug.log -e ./logs/errors.log start bot.js",
    "start-pm2": "PM2_HOME=./.pm2 pm2 -o ./logs/debug.log -e ./logs/errors.log start bot.js",
    "start-pm2-nolog": "PM2_HOME=./.pm2 pm2 -o /dev/null -e ./logs/errors.log start bot.js ",
    "stop": "killall node",
    "stop-forever": "forever stop bot.js",
    "stop-pm2": "PM2_HOME=./pm2 pm2 stop bot.js",
    "clean": "rm -rf node_modules && rm -f package-lock.json && npm install",
    "lint": "eslint ./ --cache --ignore-pattern .gitignore --fix",
    "precommit-clean": "echo \"123456\" > ./loginpin.txt && echo \"\" > ./logs/errors.log && echo \"\" > ./logs/debug.log && rm -rf /logs/screenshot/*.png && echo \"\" > ./databases/logs.db && echo \"\" > ./databases/fdf.db",
    "precommit-lint-check": "echo 'Pre-commit lint checks...' && exit 0",
    "pm2": "PM2_HOME=./.pm2 pm2"
  },
  "pre-commit": [
    "precommit-lint-check",
    "lint"
  ],
  "keywords": [
    "bot",
    "ptkdev",
    "instagram",
    "instagram-bot",
    "puppeteer",
    "selenium",
    "webdriverio"
  ],
  "dependencies": {
    "instagrambotlib": "latest",
    "yargs": "latest"
  },
  "engines": {
    "node": ">=7.6.0"
  },
  "devDependencies": {
    "eslint": "latest",
    "eslint-config-standard": "latest",
    "eslint-plugin-import": "latest",
    "eslint-plugin-node": "latest",
    "eslint-plugin-promise": "latest",
    "eslint-plugin-snakecasejs": "latest",
    "eslint-plugin-standard": "latest",
    "pre-commit": "latest",
    "pm2": "latest"
  }
}

**Comment by DeltaFox0018** [comment]
Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.6/node-v57-linux-arm64.tar.gz

**Comment by ptkdev** [comment]
Fixed in **latest** release.
