### ISSUE TITLE
Warning when following

### ISSUE THREAD

**Issue by lollymouth** [social-manager-tools/socialmanagertools-igbot#163]
Yesterday I got that warning a lot:
```
[INFO] fdf_classic: try follow
[INFO] fdf_classic: username ...
[INFO] fdf_classic: button text before click: Following
[INFO] fdf_classic: button text after click: Following
[WARNING] fdf_classic: not follow
```

bot_followday is 200

**Comment by ptkdev** [comment]
Fixed in latest releases.

**Comment by vinicoliveira** [comment]
is it still working?
[WARNING] fdf_classic: not follow
[INFO] fdf_classic: time night: 1742
[INFO] fdf_classic: loading... Fri Mar 06 2020 17:42:19 GMT+0000 (GMT)
[INFO] fdf_classic: cache array size 21
[INFO] fdf_classic: fdf_get_urlpic
