### ISSUE TITLE
Feature Request - Upload file

### ISSUE THREAD

**Issue by Ermolaev-Nikolay** [social-manager-tools/socialmanagertools-igbot#173]
### Question
Is there an idea like upload file(image/video)?

**Comment by ptkdev** [comment]
In future

**Comment by ptkdev** [comment]
@Ermolaev-Nikolay we need a "mode" in config.js to run, with 10 foto to schedule in next days. Imho your code is good start, but the full feature not is ready

**Comment by ptkdev** [comment]
Ops, sorry @Ermolaev-Nikolay i not see a pull request #191. Good job!
