### ISSUE TITLE
TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by pietrondo** [social-manager-tools/socialmanagertools-igbot#176]
Hi,

I was using the previous socialmanagertools for IG and everything works fine before, now i'm using the last version on git socialmanagertools-igbot. I had install it and correct those information in config.js, seems it cannot run and came out the error:

 | ERROR           2019-06-19 22:17:07   

> TypeError: Cannot read property 'slice' of undefined

 | DOCUMENTATION   2019-06-19 22:17:07   https://docs.socialmanager.tools/igbot/api/mode/README.md#flow()
 | STACKOVERFLOW   2019-06-19 22:17:07   https://stackoverflow.com/search?q=%5Bsocial-manager-tools%5D+TypeError:%20Cannot%20read%20property%20'slice'%20of%20undefined

**Comment by ptkdev** [comment]
Sorry but v0.10 is in development. Is unstable version. Try use stable on branch master. 

Thanks for issue

**Comment by ptkdev** [comment]
**Fixed** in Social Manager Tools v0.6.6 and IGBot Library v0.9.18. 
_Remember_: update and use latest chrome version (v75)

**Please don't use unstable version v0.10**

[![](https://img.shields.io/badge/donate-paypal-005EA6.svg)](http://paypal.ptkdev.io) [![](https://img.shields.io/badge/donate-patreon-F87668.svg)](http://patreon.ptkdev.io) [![](https://img.shields.io/badge/donate-opencollective-5DA4F9.svg)](http://opencollective.ptkdev.io) [![](https://img.shields.io/badge/buy%20me-coffee-4B788C.svg)](http://coffee.ptkdev.io) [![](https://img.shields.io/badge/help-support@ptkdev.io-fbbc05.svg)](mailto:support@ptkdev.io)
