### ISSUE TITLE
Follow ->  Not follow

### ISSUE THREAD

**Issue by cannarelladev** [social-manager-tools/socialmanagertools-igbot#177]
**Versions**

Bot Version: v0.09.17
Operating System: Windows 10
Browser: Google Chrome v69
Mode: FDF_Mode

### Expected Behavior

AAAA-MM-GG HH:MM:SS [INFO] button text before click: Follow
AAAA-MM-GG HH:MM:SS [INFO] button text after click: Following
AAAA-MM-GG HH:MM:SS [WARNING] follow

### Actual Behavior

AAAA-MM-GG HH:MM:SS [INFO] button text before click: Follow
AAAA-MM-GG HH:MM:SS [INFO] button text after click: **Follow**
AAAA-MM-GG HH:MM:SS [WARNING] **not follow**

### Steps to Reproduce

i don't know, first following from the start works perfect, the others show that kind of error/warning

In DEBUG mode the bot doesn't click on "follow" button e it continues with the next user to follow, and repeat, repeat for ever

### config.js (remember to remove password)

`{
    "debug":true,
    "login":true,
    "ui":true,
    "instagram_username":"edgardomariagiorgi",
    "instagram_password":"",
    "instagram_hashtag":["artoftheday",
    "gallery",
    "paint",
    "instaart",
    "creative",
    "artwork",
    "painting",
    "ispiration",
    "pencil",
    "drawing",
    "drawings",
    "art",
    "artsy",
    "artistoninstagram",
    "artist",
    "artistic_dome",
    "artwork",
    "sketch",
    "arttimes",
    "italianart",
    "worldofpencils",
    "pencilacademy",
    "artmotivecollective",
    "color",
    "graphicdesign"],
    "instagram_pin":"sms",
    "bot_mode":"fdfmode_classic",
    "bot_likeday_min":"500",
    "bot_likeday_max":"600",
    "bot_sleep_night":false,
    "bot_start_sleep":"7:00",
    "bot_fastlike_min":"27",
    "bot_fastlike_max":"32",
    "bot_superlike_n":"3",
    "bot_followday":"200",
    "bot_followrotate":"20",
    "bot_userwhitelist":[""],
    "comment_mode": {
        "comments": {
            "type": "array", "source": ["I like your art 👍", " very interesting picture! 🆒", " Cool Drawing! 💯"]
        }
    }
    ,
    "likemode_competitor_users": {
        "account": ""
    }
    ,
    "chrome_headless":"disabled",
    "chrome_options":["--disable-gpu",
    "--no-sandbox",
    "--window-size=1920x1080"],
    "executable_path":"C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
    "fdfdatabase_path":"C:/Users/canna/AppData/Roaming/social-manager-tools/edgardomariagiorgi_database_fdf.db",
    "logdb_path":"C:/Users/canna/AppData/Roaming/social-manager-tools/edgardomariagiorgi_database_logs.db",
    "pin_path":"C:/Users/canna/AppData/Roaming/social-manager-tools/edgardomariagiorgi_pin.txt",
    "log_path":"C:/Users/canna/AppData/Roaming/social-manager-tools/edgardomariagiorgi_fdfmode_classic.log",
    "logerr_path":"C:/Users/canna/AppData/Roaming/social-manager-tools/edgardomariagiorgi_fdfmode_classic_errors.log",
    "screenshot_path":"C:/Users/canna/AppData/Roaming/social-manager-tools/screenshot_edgardomariagiorgi/",
    "log": {
        "drivers":["console"],
        "screenshot":false,
        "channels": {
            "console":"",
            "slack": {
                "webhook": ""
            }
        }
    }
}
`

**Comment by ptkdev** [comment]
These days, instagram servers in Europe are down, it's difficult to test and fix the bugs. For example, today hashtags have "no photos". Stay tuned...

**Comment by ptkdev** [comment]
**Fixed** in Social Manager Tools v0.6.6 and IGBot Library v0.9.18. 
_Remember_: update and use latest chrome version (v75)

[![](https://img.shields.io/badge/donate-paypal-005EA6.svg)](http://paypal.ptkdev.io) [![](https://img.shields.io/badge/donate-patreon-F87668.svg)](http://patreon.ptkdev.io) [![](https://img.shields.io/badge/donate-opencollective-5DA4F9.svg)](http://opencollective.ptkdev.io) [![](https://img.shields.io/badge/buy%20me-coffee-4B788C.svg)](http://coffee.ptkdev.io) [![](https://img.shields.io/badge/help-support@ptkdev.io-fbbc05.svg)](mailto:support@ptkdev.io)
