### ISSUE TITLE
Follow/DeFollow doesn't seem to work

### ISSUE THREAD

**Issue by Sletheren** [social-manager-tools/socialmanagertools-igbot#179]
# Description:
When choosing the `fdfmode_realistic` with the config (Nightly version):
`{
			"hashtags": ["nature"], // recommended more than 20
			"followday": "100",   // number of follow-defollow user/day, work in fdfmode_classic. In 2018 limit instagram is 500/day
			"followrotate": "20", // follow 30 users, and defollow the first followed at 31 follow (in loop). If is 0 defollow all followed users previously by bot
			"userwhitelist": [], // don't defollow this users
			"sleep_night": "disabled",  // if you need stop bot in night
			"sleep_end": "7:00",        // sleep from 00:00 to 7:00 am
			"database": {
				"default": "./databases/fdfmode_classic.json" // json databases with modes info for better report
			},
		},`

I get that `Follow! OK!` but no one has been followed when checking the account.
And furthermore I get this:

![Screenshot 2019-07-09 at 16 41 04](https://user-images.githubusercontent.com/12659402/60897551-99ac1180-a268-11e9-9179-c75d54a6c485.png)
![Screenshot 2019-07-09 at 16 20 41](https://user-images.githubusercontent.com/12659402/60897552-99ac1180-a268-11e9-84c9-f4e3ee91ba21.png)

**Comment by ptkdev** [comment]
**Fixed** in Social Manager Tools v0.6.6 and IGBot Library v0.9.18. 
_Remember_: update and use latest chrome version (v75)

**Please don't use unstable version: v0.10**

[![](https://img.shields.io/badge/donate-paypal-005EA6.svg)](http://paypal.ptkdev.io) [![](https://img.shields.io/badge/donate-patreon-F87668.svg)](http://patreon.ptkdev.io) [![](https://img.shields.io/badge/donate-opencollective-5DA4F9.svg)](http://opencollective.ptkdev.io) [![](https://img.shields.io/badge/buy%20me-coffee-4B788C.svg)](http://coffee.ptkdev.io) [![](https://img.shields.io/badge/help-support@ptkdev.io-fbbc05.svg)](mailto:support@ptkdev.io)
