### ISSUE TITLE
likemode_competitior_user can't start

### ISSUE THREAD

**Issue by aldghost** [social-manager-tools/socialmanagertools-igbot#180]
its always showing
"Hashtag list is empty"
but it doesn't have hashtag tab

**Comment by ptkdev** [comment]
Workaround: set hashtag, min like/daily in realistic_mode and try start likemode_competitior_user.

**Comment by ptkdev** [comment]
**Fixed** in Social Manager Tools v0.6.6 and IGBot Library v0.9.18. 
_Remember_: update and use latest chrome version (v75)

[![](https://img.shields.io/badge/donate-paypal-005EA6.svg)](http://paypal.ptkdev.io) [![](https://img.shields.io/badge/donate-patreon-F87668.svg)](http://patreon.ptkdev.io) [![](https://img.shields.io/badge/donate-opencollective-5DA4F9.svg)](http://opencollective.ptkdev.io) [![](https://img.shields.io/badge/buy%20me-coffee-4B788C.svg)](http://coffee.ptkdev.io) [![](https://img.shields.io/badge/help-support@ptkdev.io-fbbc05.svg)](mailto:support@ptkdev.io)
