### ISSUE TITLE
Session Ban

### ISSUE THREAD

**Issue by cannarelladev** [social-manager-tools/socialmanagertools-igbot#183]
### Versions

- **Bot Version:** v0.9.18
- **Node Version:** v10.0 (Bot require >= latest lts version)
- **Operating System:** Windows 10
- **Browser:** Google Chrome v75
- **Mode:** fdfmode_classic

### Expected Behavior

One solution could be:
if the bot receives the error it could anticipate the sleep phase and after the timer expires, re-enter the access for a new session, bypassing the ban

### Actual Behavior

After the changes made by instagram I noticed that, during the fdf mode, the bot log often showed the same error:

[INFO] button text before click: follow
[INFO] button text after click: follow
[INFO] follow

so I tried to understand the problem in debug mode and discovered that instagram seems to ban the "session" (ig access) blocking the follow/unfollow. practically re-doing access with the bot, starting a new "session", the ban ceases to exist and you can again follow / unfollow

### Steps to Reproduce

1. 300 max follower/day - 30 follow rotate
2. if you receive "not follow" error go to n.3
3. in debug mode check if you receive an action ban notice
4. restart the bot (new login) and it should work again

### Screenshots (Optional)

i will upload soon

**Comment by ptkdev** [comment]
Thanks for you feedback and analysis

**Comment by holdusback** [comment]
Got this issue too but just with like. Got my acc "banned" I just had to change my password and everything became normal.

**Comment by ptkdev** [comment]
@holdusbackno **fix aren't available** beacause instagram in august 2019 decrease actions/daily to _300_. Set _250_ likes/daily and you not give `change password warning`.

**Comment by ptkdev** [comment]
Duplicate #196
