### ISSUE TITLE
[ERROR] like_superlike

### ISSUE THREAD

**Issue by asherism** [social-manager-tools/socialmanagertools-igbot#184]
```
[WARNING] like_superlike: check if current hashtag have photos, you write it good in config.js? Bot go to next hashtag.
[ERROR] like_superlike: like_get_urlpic_user error Error: Protocol error (Page.navigate): Invalid parameters url: string value expected
TypeError: Cannot read property 'split' of undefined
    at Likemode_superlike.like_get_urlpic_user (/app/modules/mode/likemode_superlike.js:204:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Versions

- **Bot Version:** latest docker image
- **Operating System:** raspberry pi
- **Mode:** like_superlike

### Expected Behavior

bot must continue to like posts

### Actual Behavior

bot stops without timeout and requires manual intervention

### Steps to Reproduce

let bot run in like_superlike mode for a while

**Comment by ptkdev** [comment]
**v0.10** is in alpha, please use **0.9.X**
