### ISSUE TITLE
fdfmode_classic - defollow only not working

### ISSUE THREAD

**Issue by JannikZed** [social-manager-tools/socialmanagertools-igbot#200]
### Versions

- **Bot Version:** v0.9.19
- **Node Version:** v12.0 (Bot require >= latest lts version)
- **Operating System:** MacOS
- **Browser:** Google Chrome v69
- **Mode:** lfdfmode_classic

I had some issues with the fdf_mode so I want the bot now to just defollow all the previously followed accounts. 
In the settings file I set: `"bot_followrotate": 0, `

### Expected Behavior

unfollow all accounts previously followed. 

### Actual Behavior
Chrome is just closing the tab and the bot is failing:
``` 
[ERROR] fdf_classic: goto Error: Navigation failed because browser has disconnected!
```

**Comment by ptkdev** [comment]
Fixed in **latest** version.
