### ISSUE TITLE
IG bot always freezing.

### ISSUE THREAD

**Issue by galinickel** [social-manager-tools/socialmanagertools-igbot#208]
### Versions

- **Bot Version:** v0.10.0
- **Node Version:** v10.0 (Bot require >= latest lts version)
- **Operating System:** Windows 10
- **Browser:** Google Chrome v80
- **Mode:** likemode_superlike

### Expected Behavior

...for the bot to run smoothly uninterrupted
### Actual Behavior

my bot is constantly freezing, whether i use the CLI ig bot or the social tools. sometimes after 3 minutes, sometimes after an hour, but my bot always freezes. it will stop responding and the only thing possible will be to force-close it.

ive tried:
-running as admin/compatibility mode with windows 7
-updating chrome/ig bot
### Steps to Reproduce

1. ...
2. ...
3. ...

### config.js (remember to remove password)
module.exports = {
	// InstagramBot.js Configs
	"debug": true,
	"login": true,
	"ui": false, // only for social-manager-tools

	// Instagram Account
	"instagram_username": "username", // without @
	"instagram_password": "password",
	"instagram_hashtag": ["himekaji", "cottagecore", "darkacademia", "darkacademiaaestheitc", "loleeta", "90slolita", "himekaji", "nymphetfashion", "nymphstyle", "himekaji", "himegyaru", "farmstyle", "farmcore", "cottagecoreaesthetic", "angelcore", "fairycore", "dollcore", "softcore", "vintagestyle", "pinkstyle", "pinkfeed", "beigefeed", "softfeed", "softgirl", "artcore", "plantcore", "plants", "kawaii", "kawaiigirl", "kawaiifashion", "kawaiistyle"], // without #, recommended more than 20
	"instagram_pin": "sms", // method to receive pin (email or sms)

	// BOT Configs
	// [WORK] likemode_classic          - select random hashtag from config list and like 1 random photo (of last 20) | 400-600 like/day.
	// [WORK] likemode_realistic        - select random hashtag from config list, like fast 10-12 photo and sleep 15-20min. Sleep at night
	// [WORK] likemode_superlike        - select random hashtag from config list and like 3 random photo of same user | 400-600 like/day.
	// [WORK] likemode_competitor_users - select account, select random followers, like 10-12 photo and sleep 15-20min.
	// [WORK] comment_mode              - leave a comment under the photo via hashtag.
	// [WORK] fdfmode_classic           - follow 30 users, and defollow the first followed at 31 follow (in loop). This method is not detected from socialblade. ~1h | 300/300 follow-defollow/day.
	"bot_mode": "likemode_superlike",
	"bot_likeday_min": 500,      // work in all likemode_*
	"bot_likeday_max": 700,      // work in all likemode_*. In 2018 limit instagram is 1000/day
	"bot_sleep_night": true,    // if you need stop bot in night
	"bot_start_sleep": "7:00",   // sleep from 00:00 to 7:00 am, work in likemode_realistic, comment_mode, likemode_superlike and likemode_competitor_users
	"bot_superlike_n": 6,        // superlike number of likes for user
	"bot_followday": 300,        // number of follow-defollow user/day, work in fdfmode_classic. In 2018 limit instagram is 500/day
	"bot_followrotate": 30,      // follow 30 users, and defollow the first followed at 31 follow (in loop), work in fdfmode_classic | If is 0 defollow all followed previously by bot
	"bot_userwhitelist": ["user1", "user2", "user3"],   // usernames without @ | don't defollow this users on follow-defollow mode, work in fdfmode_classic
	"comment_mode": {
		"comments": {
			"type": "array",
			"source": ["comment1", "comment2", "comment3"],
		}
	},
	"likemode_competitor_users": {
		"account": "user_nickname" // without @
	},

	// Puppeteer Configs
	"chrome_headless": true,
	"chrome_options": ["--disable-gpu", "--no-sandbox", "--window-size=1024x768"],
	"chrome_options": ["--window-size=1920x1080", "--proxy-server=171.22.191.233:21313"],
	"executable_path": "", // example for Mac OS: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

	// DATABASES
	"fdfdatabase_path": "./databases/fdf.db", // databases with username of followed users with follodefollow mode
	"logdb_path": "./databases/logs.db",      // logs in sqllite database for better report

	// LOG
	"pin_path": "./loginpin.txt",
	"log_path": "./logs/debug.log",
	"logerr_path": "./logs/errors.log",
	"screenshot_path": "./logs/screenshot/",
	"log": {
		"drivers": ["console"], // slack or console
		"screenshot": false,  // disable or enable screenshot in logs folder
		"channels": {
			"console": "",
			"slack": {
				"webhook": ""
			}
		}
	}
};

```

### Screenshots (Optional)

**Comment by ptkdev** [comment]
Don't use v0.10 are unstable, use **master** branch.

**Comment by galinickel** [comment]
> Don't use v0.10 is unstable, use **master** branch or [desktop app](https://socialmanager.tools/).

it still freezes when using the desktop app unfortunately.

**Comment by ptkdev** [comment]
@galinickel run app with `debug:enabled`

**Comment by galinickel** [comment]
> @galinickel run app with `debug:enabled`

i tried that, unfortunately it still freezes... the instagram page will be stuck on an error page (looks like the page youre looking for doesnt exist) and the app will freeze completely, rendering it unresponsive.

**Comment by ptkdev** [comment]
You use hashtags without photos. Check typing errors

**Comment by galinickel** [comment]
heyo :) 
upon further testing, all my tags hav e photos. it freezes when trying to access a profile, the browser goes to an error page saying the link doesnt exist or is broken, and the app freezes all together.

**Comment by abscess** [comment]
Does the proxy server bother you? ```--proxy-server=171.22.191.233:21313``

**Comment by galinickel** [comment]
> Does the proxy server bother you? `--proxy-server=171.22.191.233:21313`

same result with or without it, unless you meant that i shouldnt have included it in my post in that case i removed it (sorry, im 0% coding oriented in any way)
