### ISSUE TITLE
Is it possible to enjoy like photos with less than X likes?

### ISSUE THREAD

**Issue by Rigolon** [social-manager-tools/socialmanagertools-igbot#212]
[Q] --> Is it possible to enjoy like photos with less than X likes?

### Question

Is there any way to like only photos with less than 10 likes? I would like to filter to have a better return of the liked photos. When we like photos with many likes, we are rarely seen.

I am using realistic mode.

**Comment by ptkdev** [comment]
Nope, bot don't read number of likes of photos. This filter aren't available at moment.
